wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.14.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1681731429.170675
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 19
      - 23
      4: 3.8.16
      5: 0.14.2
      8:
      - 3
      - 5
dropout:
  desc: null
  value: 0.2
hidden_layer_size:
  desc: null
  value: 128
